# Generated by Django 4.1.3 on 2022-12-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='checks',
            field=models.BooleanField(default=False),
        ),
    ]
